version: "3.9"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alam
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce
    networks:
      - golang-network

  server:
    container_name: golang-server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9200:9200
    volumes:
      - service-golang:/golang
    network_mode: e-commerce_golang-network

volumes:
  postgres-data:
    name: postgres-data
  service-golang:
    name: service-golang

networks:
  golang-network:
    driver: bridge